### ISSUE TITLE
"Include template" highlighting

### ISSUE THREAD

**Issue by blueskies79** [kinglozzer/idea-silverstripe-plugin#9]
Thanks so much for this plugin! It's great that the idea-plugin is getting an update!

I have found some inconsistencies with the template include highlighting, that might need some attention. I think it's valid to have numbers as part of a template name, isn't it? The previous idea-plugin had issues with this naming as well. It shows the include as being erroneous. See:

![](https://user-images.githubusercontent.com/6065560/111026537-fde28980-83ea-11eb-9db3-a767a6525ac3.jpg)

Also there are inconsistencies with the coloring when using namespaced template names and "regular" includes:

Regular include:

![](https://user-images.githubusercontent.com/6065560/111026563-19e62b00-83eb-11eb-8b29-d96edaa1ecd0.jpg)

Namespaced:

![](https://user-images.githubusercontent.com/6065560/111026573-210d3900-83eb-11eb-93e7-8e67211b75a4.jpg)

This is not a major issue, but it would be visually helpful that the namespaced template names don't look like comments :-D

**Comment by kinglozzer** [comment]
Thanks for the report @blueskies79, this is really helpful! It looks like there are two issues here:

1) Numbers in template names seem to break it, `CardTopTenModel` instead of `CardTop10Model` seems to be fine
2) The annotator doesn’t like two backslashes for include references. It works with one backslash, but not two

Both of these should be fairly simple fixes, I’ll take a look soon!

**Comment by kinglozzer** [comment]
I’ve release 0.2.1 including a fix for this: https://github.com/kinglozzer/idea-silverstripe-plugin/releases. Thanks!
